import streamlit as st


st.set_page_config(
    page_title="Practice Quiz",
    page_icon="❓",
    layout="wide"
)


st.title("❓ Interactive Practice Quiz")

st.write(
    "Test your understanding and identify weak areas."
)


topic = st.selectbox(
    "Choose a topic",
    [
        "Morphology",
        "Phonology",
        "Syntax",
        "Semantics"
    ]
)


difficulty = st.select_slider(
    "Difficulty",
    options=[
        "Easy",
        "Medium",
        "Hard"
    ]
)


if st.button(
    "🎯 Generate Quiz",
    type="primary"
):

    st.info(
        f"A {difficulty.lower()} quiz for "
        f"{topic} will be generated by the AI."
    )